basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: REST API for tracking daily activities, completions, and rewards.
  title: Routine Series API
  version: 0.1.0
paths: {}
swagger: "2.0"
